### ISSUE TITLE
is this a bug or is it just my idiocy.

### ISSUE THREAD

**Issue by chessdenman** [nicklockwood/Euclid#112] opened 2024-01-31 20:12 UTC
HI Intersecting a line and a plane seems to have some problems.

    let p = Plane(normal: Vector(0,0,1), pointOnPlane: Vector(0,0,5))
    if let ls = LineSegment(start: Vector(2.5,2.5,5), end: Vector(2.5,2.5,10)) {
        let intersection = p!.intersection(with: ls)
        print(intersection)
    } else {
        print("No intersection")
    }
 

this will find the intersection one way but not the other (ie     if let ls = LineSegment(start: Vector(2.5,2.5,10), end: Vector(2.5,2.5,5))

**Comment by nicklockwood** [comment] 2024-03-06 00:31
Duplicate of https://github.com/nicklockwood/Euclid/issues/111

**Closed by nicklockwood** 2024-03-06 00:31 UTC
